# Generated by Django 6.0.5 on 2026-05-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily_sales', 'Daily Sales'), ('weekly_sales', 'Weekly Sales'), ('monthly_sales', 'Monthly Sales'), ('inventory', 'Inventory Report'), ('reservations', 'Reservation Report')], max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
